# 2022년 3월의 온오프라인 상픔 판매데이터의 판매 날짜, 상품ID,유저ID 판매량을 출력
# OFFLINE_SALE 테이블의 판매 데이터의 USER_ID 값은 NULL 

SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM(
    SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
    FROM ONLINE_SALE
UNION ALL
    SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
)T
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE ASC,PRODUCT_ID ASC,USER_ID ASC
