-- 우유와 요거트를 동시에 구입한 장바구니의 아이디 조회
-- 아이디순

SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'MILK' 
  AND CART_ID IN 
  (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'YOGURT')
ORDER BY CART_ID
