SELECT FH.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS FH_SUM
FROM FIRST_HALF 
GROUP BY FLAVOR) FH JOIN  (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_SUM
FROM JULY 
GROUP BY FLAVOR) J ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.FH_SUM + J.J_SUM) DESC
LIMIT 3
